Test for libtool in ./bootstrap and add libmysqlclient-dev to dependencylist in README

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,3 +1,5 @@
 #!/bin/sh
+type libtool 2>&1 > /dev/null
+if [ $? -gt 0 ]; then echo "Missing required libtool"; exit 1; fi
 autoreconf -i
 automake --add-missing
