runtests: error out when tools are not built

diff --git a/regression-tests/runtests b/regression-tests/runtests
--- a/regression-tests/runtests
+++ b/regression-tests/runtests
@@ -5,7 +5,6 @@ if [ -z "$testsdir" ]; then
 fi
 
 PATH=.:$PATH:/usr/sbin
-MAKE=${MAKE:-make}
 
 if [ -z "$PDNS_BUILD_PATH" ]; then
   # PDNS_BUILD_PATH is unset or empty. Assume an autotools build.
@@ -46,8 +45,9 @@ spectest=$1
 [ -z $spectest ] && spectest=""
 
 for prog in $SDIG $SAXFR $NOTIFY $NSEC3DIG; do
-  if `echo $prog | grep -q '\.\./pdns'`; then
-    ${MAKE} -C ../pdns ${prog##*../pdns/} || exit
+  if [ ! -x "$prog" ]; then
+    echo "Error: cannot find $prog, please build it."
+    exit 1
   fi
 done
 
