more testing/xml updates
git-svn-id: svn://svn.powerdns.com/pdns/trunk/pdns@2353 d19b8d6e-7fed-0310-83ef-9ca221ded41b

diff --git a/regression-tests/start-test-stop b/regression-tests/start-test-stop
--- a/regression-tests/start-test-stop
+++ b/regression-tests/start-test-stop
@@ -1,12 +1,107 @@
 #!/bin/sh -ex
+
+tosql ()
+{
+	make -C ../pdns/backends/bind zone2sql > /dev/null
+	../pdns/backends/bind/zone2sql --transactions --$1 --named-conf=./named.conf
+
+}
+
 port=$1
 [ -z "$port" ] && port=5300
-./bind-gsqlite3-setup
-../pdns/pdns_server --daemon=no --local-port=5300 --socket-dir=./  \
---no-shuffle --launch=bind,gsqlite3 --bind-config=./named.conf       \
---gsqlite3-database=./powerdns.sqlite3 --gsqlite3-dnssec             \
---fancy-records --query-logging --send-root-referral --loglevel=9    \
---cache-ttl=0 --no-config &
+context=$2
+[ -z "$context" ] && context=bind-gsqlite3
+
+case $context in
+		bind)
+			../pdns/pdns_server --daemon=no --local-port=$port --socket-dir=./  \
+				--no-shuffle --launch=bind --bind-config=./named.conf                \
+				--fancy-records --query-logging --send-root-referral --loglevel=9    \
+				--cache-ttl=0 --no-config &
+			;;
+		bind-gsqlite3)
+			./bind-gsqlite3-setup
+			../pdns/pdns_server --daemon=no --local-port=$port --socket-dir=./  \
+				--no-shuffle --launch=bind,gsqlite3 --bind-config=./named.conf       \
+				--gsqlite3-database=./powerdns.sqlite3 --gsqlite3-dnssec             \
+				--fancy-records --query-logging --send-root-referral --loglevel=9    \
+				--cache-ttl=0 --no-config &
+			;;
+		gmysql-nodnssec)
+			[ -z "$GMYSQLDB" ] && GMYSQLDB=pdnstest
+			[ -z "$GMYSQLUSER" ] && GMYSQLUSER=root
+			[ -z "$GMYSQLHOST" ] && GMYSQLHOST=localhost
+			[ -z "$GMYSQLPASSWD" ] && GMYSQLPASSWD=''
+
+			mysqladmin --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" --force drop "$GMYSQLDB" \
+				|| echo ignoring mysqladmin drop failure
+			mysqladmin --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" create "$GMYSQLDB"
+			mysql --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" \
+				"$GMYSQLDB" < ../pdns/no-dnssec.schema.mysql.sql
+
+			tosql gmysql | mysql --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" \
+				"$GMYSQLDB"
+
+			../pdns/pdns_server --daemon=no --local-port=$port --socket-dir=./  \
+				--no-shuffle --launch=gmysql \
+				--fancy-records --query-logging --send-root-referral --loglevel=9 \
+				--cache-ttl=0 --no-config \
+				--gmysql-dbname="$GMYSQLDB" \
+				--gmysql-user="$GMYSQLUSER" \
+				--gmysql-host="$GMYSQLHOST" \
+				--gmysql-password="$GMYSQLPASS" &
+			;;
+		gmysql)
+			[ -z "$GMYSQLDB" ] && GMYSQLDB=pdnstest
+			[ -z "$GMYSQLUSER" ] && GMYSQLUSER=root
+			[ -z "$GMYSQLHOST" ] && GMYSQLHOST=localhost
+			[ -z "$GMYSQLPASSWD" ] && GMYSQLPASSWD=''
+
+			mysqladmin --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" --force drop "$GMYSQLDB" \
+				|| echo ignoring mysqladmin drop failure
+			mysqladmin --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" create "$GMYSQLDB"
+			mysql --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" \
+				"$GMYSQLDB" < ../pdns/no-dnssec.schema.mysql.sql
+			mysql --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" \
+				"$GMYSQLDB" < ../pdns/dnssec.schema.mysql.sql
+
+			tosql gmysql | mysql --user="$GMYSQLUSER" --password="$GMYSQLPASSWD" --host="$GMYSQLHOST" \
+				"$GMYSQLDB"
+
+			cat > pdns-gmysql.conf << __EOF__
+launch=gmysql
+gmysql-dbname=$GMYSQLDB
+gmysql-user=$GMYSQLUSER
+gmysql-host=$GMYSQLHOST
+gmysql-password=$GMYSQLPASS
+gmysql-dnssec
+__EOF__
+			for zone in $(grep zone named.conf  | cut -f2 -d\")
+			do
+				../pdns/pdnssec --config-dir=. --config-name=gmysql	secure-zone $zone 2>&1
+			done
+
+			../pdns/pdns_server --daemon=no --local-port=$port --socket-dir=./  \
+				--no-shuffle --launch=gmysql --gmysql-dnssec \
+				--fancy-records --query-logging --send-root-referral --loglevel=9 \
+				--cache-ttl=0 --no-config \
+				--gmysql-dbname="$GMYSQLDB" \
+				--gmysql-user="$GMYSQLUSER" \
+				--gmysql-host="$GMYSQLHOST" \
+				--gmysql-password="$GMYSQLPASS" &
+			;;			
+		*)
+			echo unknown context $context
+			: > passed_tests
+			echo 'unknown-context' > failed_tests
+			./toxml $context
+			exit 1
+esac
+		
 export port
-nameserver=127.0.0.1 ./runtests
+
+## TODO: give pdns a few seconds to startup or fail, then check if it did not fail
+## TODO: give sdig a timeout
+nameserver=127.0.0.1 ./runtests $context
 kill $(cat pdns.pid)
+./toxml $context
