Sander Hoentjen <sander@hoentjen.eu>:I have a patch that add exit codes to the init-script status and start commands. This helps stuff like puppet to manage the service.
git-svn-id: svn://svn.powerdns.com/pdns/trunk/pdns@2728 d19b8d6e-7fed-0310-83ef-9ca221ded41b

diff --git a/pdns/pdns.in b/pdns/pdns.in
--- a/pdns/pdns.in
+++ b/pdns/pdns.in
@@ -54,6 +54,7 @@ case "$1" in
 			echo $ret
 		else
 			echo "not running"
+			exit 3
 		fi 
 	;;	
 
@@ -84,6 +85,9 @@ case "$1" in
 			if $pdns_server --daemon --guardian=yes
 			then
 				echo "started"	
+	            	else
+				echo "starting failed"
+		                exit 1
 			fi
 		fi 
 	;;		
