Build release packages properly

diff --git a/build-scripts/build-dnsdist-rpm b/build-scripts/build-dnsdist-rpm
--- a/build-scripts/build-dnsdist-rpm
+++ b/build-scripts/build-dnsdist-rpm
@@ -10,6 +10,10 @@ if [ -z "$VERSION" ]; then
   exit 1
 fi
 
+if [ -z "$TARBALLVERSION" ]; then
+  TARBALLVERSION=${VERSION}
+fi
+
 if [ -z "$RELEASE" ];then
   echo 'Please set $RELEASE' >&2
   exit 1
@@ -22,10 +26,10 @@ set -x
 rpmdev-setuptree
 
 # This is somethat ugly...
-if [ -f dnsdist-${VERSION}.tar.bz2 ]; then
-  mv dnsdist-${VERSION}.tar.bz2 $HOME/rpmbuild/SOURCES
+if [ -f dnsdist-${TARBALLVERSION}.tar.bz2 ]; then
+  mv dnsdist-${TARBALLVERSION}.tar.bz2 $HOME/rpmbuild/SOURCES
 else
-  echo "dnsdist-${VERSION}.tar.bz2 not found" >&2
+  echo "dnsdist-${TARBALLVERSION}.tar.bz2 not found" >&2
   exit 1
 fi
 
@@ -44,7 +48,7 @@ DEFAULTS_INSTALL=''
 DEFAULTS_FILES=''
 
 # On some older distro's *cough* centos 6 *cough* autosetup fails
-SETUP='%autosetup -n %{name}-%{version}'
+SETUP="%autosetup -n %{name}-${TARBALLVERSION}"
 
 # Some setups need rpmbuild in a 'special' env
 RPMBUILD_COMMAND='rpmbuild -bb dnsdist.spec'
@@ -60,7 +64,7 @@ if [ -f /etc/redhat-release ]; then
       INIT_BUILDREQUIRES=''
       INIT_INSTALL='install -d -m 755 %{buildroot}/%{_initrddir} && install -m 755 contrib/dnsdist.init.centos6 %{buildroot}/%{_initrddir}/dnsdist'
       INIT_FILES='%{_initrddir}/dnsdist'
-      SETUP='%setup -n %{name}-%{version}'
+      SETUP="%setup -n %{name}-${TARBALLVERSION}"
       RPMBUILD_COMMAND="scl enable devtoolset-2 -- ${RPMBUILD_COMMAND}"
       ;;
     CentOS\ Linux\ *\ 7*)
@@ -81,7 +85,7 @@ Summary: Powerful and scriptable DNS loadbalancer
 License: GPLv2
 Vendor: PowerDNS.COM BV
 Group: System/DNS
-Source: dnsdist-${VERSION}.tar.bz2
+Source: dnsdist-${TARBALLVERSION}.tar.bz2
 BuildRequires: readline-devel
 BuildRequires: boost-devel
 BuildRequires: lua-devel
diff --git a/build-scripts/build-recursor-rpm b/build-scripts/build-recursor-rpm
--- a/build-scripts/build-recursor-rpm
+++ b/build-scripts/build-recursor-rpm
@@ -10,6 +10,10 @@ if [ -z "$VERSION" ]; then
   exit 1
 fi
 
+if [ -z "$TARBALLVERSION" ]; then
+  TARBALLVERSION=${VERSION}
+fi
+
 if [ -z "$RELEASE" ];then
   echo 'Please set $RELEASE' >&2
   exit 1
@@ -22,10 +26,10 @@ set -x
 rpmdev-setuptree
 
 # This is somethat ugly...
-if [ -f pdns-recursor-${VERSION}.tar.bz2 ]; then
-  mv pdns-recursor-${VERSION}.tar.bz2 $HOME/rpmbuild/SOURCES
+if [ -f pdns-recursor-${TARBALLVERSION}.tar.bz2 ]; then
+  mv pdns-recursor-${TARBALLVERSION}.tar.bz2 $HOME/rpmbuild/SOURCES
 else
-  echo "pdns-recursor-${VERSION}.tar.bz2 not found" >&2
+  echo "pdns-recursor-${TARBALLVERSION}.tar.bz2 not found" >&2
   exit 1
 fi
 
@@ -112,7 +116,7 @@ Summary: Modern, advanced and high performance recursing/non authoritative name 
 Group: System Environment/Daemons
 License: GPLv2
 URL: http://powerdns.com
-Source0: ../%{name}-%{version}.tar.bz2
+Source0: ../%{name}-${TARBALLVERSION}.tar.bz2
 Source1: pdns-recursor.init
 
 Provides: powerdns-recursor = %{version}-%{release}
@@ -129,9 +133,9 @@ PowerDNS Recursor is a non authoritative/recursing DNS server. Use this
 package if you need a dns cache for your network.
 
 %prep
-%setup -q
-sed -i -e 's!SYSCONFDIR=/etc/powerdns!SYSCONFDIR=/etc/pdns-recursor!' -e 's!STRIP_BINARIES?=1!STRIP_BINARIES?=0!' $HOME/rpmbuild/BUILD/pdns-recursor-${VERSION}/Makefile.in
-sed -i -e 's!OS_SPECIFIC_INSTALL=.*!OS_SPECIFIC_INSTALL=!' $HOME/rpmbuild/BUILD/pdns-recursor-${VERSION}/sysdeps/Linux.inc
+%setup -q -n pdns-recursor-${TARBALLVERSION}
+sed -i -e 's!SYSCONFDIR=/etc/powerdns!SYSCONFDIR=/etc/pdns-recursor!' -e 's!STRIP_BINARIES?=1!STRIP_BINARIES?=0!' $HOME/rpmbuild/BUILD/pdns-recursor-${TARBALLVERSION}/Makefile.in
+sed -i -e 's!OS_SPECIFIC_INSTALL=.*!OS_SPECIFIC_INSTALL=!' $HOME/rpmbuild/BUILD/pdns-recursor-${TARBALLVERSION}/sysdeps/Linux.inc
 
 %build
 %configure
@@ -197,7 +201,7 @@ Summary: Modern, advanced and high performance recursing/non authoritative name 
 Group: System Environment/Daemons
 License: GPLv2
 URL: http://powerdns.com
-Source0: ../%{name}-%{version}.tar.bz2
+Source0: ../%{name}-${TARBALLVERSION}.tar.bz2
 
 Provides: powerdns-recursor = %{version}-%{release}
 BuildRequires: boost-devel
@@ -216,9 +220,9 @@ PowerDNS Recursor is a non authoritative/recursing DNS server. Use this
 package if you need a dns cache for your network.
 
 %prep
-%setup -q
-sed -i -e 's!SYSCONFDIR=/etc/powerdns!SYSCONFDIR=/etc/pdns-recursor!' -e 's!STRIP_BINARIES?=1!STRIP_BINARIES?=0!' $HOME/rpmbuild/BUILD/pdns-recursor-${VERSION}/Makefile.in
-sed -i -e 's!OS_SPECIFIC_INSTALL=.*!OS_SPECIFIC_INSTALL=!' $HOME/rpmbuild/BUILD/pdns-recursor-${VERSION}/sysdeps/Linux.inc
+%setup -q -n pdns-recursor-${TARBALLVERSION}
+sed -i -e 's!SYSCONFDIR=/etc/powerdns!SYSCONFDIR=/etc/pdns-recursor!' -e 's!STRIP_BINARIES?=1!STRIP_BINARIES?=0!' $HOME/rpmbuild/BUILD/pdns-recursor-${TARBALLVERSION}/Makefile.in
+sed -i -e 's!OS_SPECIFIC_INSTALL=.*!OS_SPECIFIC_INSTALL=!' $HOME/rpmbuild/BUILD/pdns-recursor-${TARBALLVERSION}/sysdeps/Linux.inc
 
 %build
 %configure
